sudo: required
language: node_js
node_js:
- 8.11.4
cache:
  directories:
    - "node_modules"
before_deploy:
- npm build
deploy:
- provider: npm
  email: NOT_NEEDED
  api_key: NOT_NEEDED
  on:
    tags: true
  skip_cleanup: true
