sudo: required
language: node_js
node_js:
- 8.11.4
cache:
  directories:
  - node_modules
addons:
  chrome: stable
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
- export PATH="$HOME/.yarn/bin:$PATH"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_deploy:
- yarn build
deploy:
  provider: npm
  email: engineering-npm@optimizely.com
  api_key:
    secure: tDiKenRfrNavooI2iKybybdQGb1dQJRJwF3eSFmcDb+gucQQ47YysGd3Oppc7GkPbmMmGAnsKTZp4+TOwGxEUk/3txqUw4ypixWqYzP5+B0M4/yK9vpXH5iwDHYk6z/rp6jsTqV4ioE3ZQC3SCHNot1N5agEvfbH120FLjvXGhFJ+qzOol846iVvsfMPBNsobKTZDMuB/+rDbUXYaAK2MWxqQxns81a1o0cudIK3PK+F2dNwOQgyMFIR3ZbOgX1Mo0miETcXg6AhEDzBuNBaAvxX8MuxdO/lZMDtUlqrMedV0JO35OQbpvs3SgRiqH9omfXRD+QO+kN0s+p6fUjRUi9bUssTLj1czBiU+sROaveHlM9hjKCc1KywK4xcYc0bGCAf8ff4T2+WQJ28zLKjMUa8etCuXTqe6gERVwvWuaNZSbxKnA6DOv2amGX1M7r+W98GonhpXA4lcVqqJxwT4q7j70jx6COFXTQ0PmdGSEcU8+ykfu6yWtzhbYa6pXdgY/JcrXai4evbiXDdKt4+c+9I6KK5v6JyawJKlM6qdEPMTo+FaOvtnW9Kh6kRcOXshpIvBqB8QSUTLVv127FijMmcaaSLqEfqGzqSU6U2+OJd+RX09vdarCPgtFEpXpyuI6Z9sIzitrKkDcA0FiF70Pb4d/+8AdIH+RqMOzt2v4A=
  on:
    tags: true
    repo: optimizely/nuclear-router
