sudo: required
language: node_js
node_js:
- 8.11.4
cache:
  directories:
  - node_modules
addons:
  chrome: stable
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
- export PATH="$HOME/.yarn/bin:$PATH"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_deploy:
- yarn build
deploy:
  provider: npm
  email: engineering-npm@optimizely.com
  api_key:
    secure: hLhUK++HLHpuqfpLuIdgiOR3YHfKuIuDBASauu7vQwZcImyNXubOf7uZ5DhtY7SUxpcSzTuhpFIPUyW831A67DHHDcCI3oPgdWkqRROX6D4URNVquQwDbZdb6W6bcJkQVe84d/JA/b/QzHrcyfGBTpj90737DJheTJ+EwuR7Rr1NsNjtxLJADjlIamt5/Sn2wXykbqxcA7xFElfH0kHCRksuJKuN0AeMTX0/CaAdm+hAakcEUEaToqavRqfx+7p5xAHfTIqcq0g2SyxBSnDgiDlQ1pVxrNVI/xIayVaxDSR6RB4zMgQdgf9iimgdg4wwzVvJH9QoK5W1x0Xoz/gwmEa23FaUu+PidoleU5YIKP+jgsBk5olO2KJSUT5ux9P7KLn+iDi0GO+s1+nnXtdZSjmLt1G77W6/+4ucJdx33rGEMjNDkNfGmbuBfM5Ih5CUhqT8PHwpHNAtyzSyoTFQBTPfFjWrQXphqecHZHaOyJ6YK/8wpORTUslJdyF6i6Vamf+y+2rJmYhaIc7Isp0Zz9y8NW4q7bzTi5YwDkSRVRW72l63oMz14FSI59fHD3gG/gVft4ta0dKkwzNuVrPcS4m4Hzfk9wScNf1XAFeHjtYFS/kJhdOwcBotVt0+0CBtFHnYLtuYLG5qhTmZwjnkREIWPlXOewRyueDYXLT4KN8=
  on:
    tags: true
    repo: optimizely/nuclear-router
